### ISSUE TITLE
Angular version not booting for me

### ISSUE THREAD

**Issue by bradrice** [valor-software/nativescript-plugins#15]
I followed the angular instructions, but I'm just getting errors when I try to run ns debug ios.

`
***** Fatal JavaScript exception - application has been terminated. *****
  NativeScript encountered a fatal error:
  Error calling module function
  TypeError: Cannot read properties of undefined (reading 'windowScene')
  File: (file: app/webpack:/class2tns/webpack/bootstrap:27:0)
  StackTrace:
  	requestReviewPopup(file: app/webpack:/class2tns/node_modules/@valor/nativescript-in-app-review/index.ios.js:9:57)
  	at ./app/app.component.ts(file: app/webpack:/class2tns/app/app.component.ts:5:0)
  	at __webpack_require__(file: app/webpack:/class2tns/webpack/bootstrap:24:0)
  	at fn(file: app/webpack:/class2tns/webpack/runtime/hot module replacement:62:0)
  	at ./app/app.module.ts(file:///app/bundle.js:198:72)
  	at __webpack_require__(file: app/webpack:/class2tns/webpack/bootstrap:24:0)
  	at fn(file: app/webpack:/class2tns/webpack/runtime/hot module replacement:62:0)
  	at ./app/main.ts(file:///app/bundle.js:14:69)
  	at __webpack_require__(file: app/webpack:/class2tns/webpack/bootstrap:24:0)
  	at __webpack_exec__(file:///app/bundle.js:12682:39)
  	at (file:///app/bundle.js:12683:189)
  	at __webpack_require__.X(file: app/webpack:/class2tns/webpack/runtime/startup entrypoint:6:0)
  	at (file:///app/bundle.js:12683:47)
  	at (file:///app/bundle.js:12688:3)
  	at require(:1:232)`

**Comment by bradrice** [comment]
My bad. I needed to make the call on a route inside deeper into the app instead of on the root route.
